---
- name: Install BIND9
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: Deploy BIND9 forwarders config
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: '0644'
    
- name: Enable and start BIND9
  service:
    name: bind9
    state: started
    enabled: yes

