network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.3.1/24
      routes:
        - to: 192.168.1.0/24
          via: 192.168.3.2
        - to: 192.168.2.0/24
          via: 192.168.3.2
