network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.1/24
    eth1:
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.0.0.1/30
      routes:
        - to: 192.168.2.0/24
          via: 10.0.0.2
    eth2:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.3.2/24
      routes:
        - to: 192.168.3.0/24
          via: 192.168.3.1
