network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 192.168.111.11/24   # internal
    eth1:
      addresses:
        - 10.100.1.11/24      # DMZ
      gateway4: 10.100.1.10
      nameservers:
        addresses:
          - 8.8.8.8
    
